import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <div className="min-h-[calc(100vh-3.5rem)] bg-background py-12 sm:py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6">
        <div className="bg-white rounded-xl border border-border shadow-md p-6 sm:p-10 animate-fade-in-up">
          <Link
            to="/"
            className="inline-flex items-center gap-1 text-sm text-accent hover:text-accent/80 mb-6 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
            Back to Home
          </Link>

          <h1 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mb-8">Last updated: June 2025</p>

          <div className="space-y-6 text-sm sm:text-base text-foreground leading-relaxed">
            <section>
              <h2 className="font-heading text-lg font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By using Fuenzer Career, you agree to these Terms of Service. If you do not agree, please do not use the platform.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold text-foreground mb-2">2. Use of Service</h2>
              <p className="text-muted-foreground">
                Fuenzer Career provides AI-powered mock interview practice. You agree to use the service only for lawful purposes and not to:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-muted-foreground">
                <li>Upload harmful, obscene, or illegal content.</li>
                <li>Attempt to reverse-engineer or abuse the AI systems.</li>
                <li>Use the platform to impersonate others.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold text-foreground mb-2">3. Account Responsibility</h2>
              <p className="text-muted-foreground">
                If you create an account, you are responsible for maintaining the confidentiality of your password and for all activity under your account.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold text-foreground mb-2">4. Disclaimer</h2>
              <p className="text-muted-foreground">
                Fuenzer Career is a practice tool and does not guarantee job placement or interview success. Feedback is generated by AI and may not be error-free. Use it as a supplement to your own preparation.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold text-foreground mb-2">5. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                Fuenzer Career and its operators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold text-foreground mb-2">6. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We may update these terms from time to time. Continued use after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold text-foreground mb-2">7. Contact</h2>
              <p className="text-muted-foreground">
                For questions about these terms, contact{" "}
                <a href="mailto:fuenzerofficial@gmail.com" className="text-accent hover:text-accent/80 underline underline-offset-2 transition-colors">
                  fuenzerofficial@gmail.com
                </a>.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}